language: node_js
after_success:
  - bash deploy.sh
env:
  global:
    - secure: "iI8LV3qhegCsCa1thFqnoswZA6HAfso3W540Ey80+jQqJWLgQwG8mx/WSgZqhwaglsk9AqPnxIlbbAfymC/dgkHnHs/WprZulGEtlSAnWQjUs98y0Ss2Ui+wYFaH5oHlhz3SyLCw1YemoRZxhLYgdvKGfn5FSJgr8ahSEbAa/4zUlLOftqZHhKfGHZRG0gKAJ6JzvvqLBzwtl0F8FRSYXa1DdMe6WT6BTMgDmek96whV0SOaLlIXIrnPsL+hoCPgXvA+Hini+jyod2/85hLqOF8TQNxPoEsZXUgQB5cOBizd4rIrSJQOHjKLSE9HIdkbsAnjcHI6zNbzhgmthkmOhd6tOlcVxQF3NsPTpUdwt1L0SWtPvuGEUDP5i8KLKDDeMZOvC1NbSSgqq51NMHeWgz6f7hOwtOsquv7Lskwv51iswOenQjU4l4x684OTvi12bIp/8npkCJqYIizktl/Zxg8QQQO4IsuxoToDaT3Nl6Pm87iyJKagMv0BNo6Bu8eqr/LX5I116+9tUDEWyTWLkvamjyeZjW8lLDN0t7Heb1+fa6N1PnP+Rw3G2BmuTNmC120iCA0ljOdpjSKBgkMtxyFDQrbDZZw8QuwcmyWXjFIh/i74WW6ujN/BwojrGyrs2z0XIu8Q0cFdMHypfuFuNuRsEhhTcW8IE+f9SMbrFck="
